server:
  port: 8848
  servlet:
    context-path: /yml

person:
  username: "易烊千玺"
  password: "123456"

student:
  name: '钟\r\n离'
  age: 22
  gender: '男'
  married: false                      # 布尔
  birthday: 2000/11/28 10:00:01       # 日期
  info: '原神'
  hobby: ["摩拉克斯", "武神"]  # 数组
  food:                                # 集合
    - 一份惆怅
    - 一份凄凉
    - 老坛酸菜面
    - 双汇火腿肠
  score: {"Java": 100, "MySQL": 10}   # Map
  car:                                # 对象
    name: BYD·唐
    color: 白色